#!/bin/bash

# Correct commands for interacting with Atlas Protocol contracts

RPC_URL="https://rpc-storyevm-testnet.aldebaranode.xyz"
IDO_ADDRESS="0x5b7575272cb12317eb5d8e8d9620a9a34a7a3de4"
ADLV_ADDRESS="0xF8C5804Bdf6875EBB6cCf70Fc7f3ee6745Cecd98"
PRIVATE_KEY="0x6d404905f552f930a111937f77cc6554f6c8b6e5e0f488c909cea190dcbe8c59"

# Example IP ID (replace with your actual IP ID)
IP_ID="0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"

echo "=========================================="
echo "Correct Contract Interaction Commands"
echo "=========================================="
echo ""

echo "1. Create Vault (CORRECT)"
echo "   Function: createVault(bytes32)"
echo "   Note: Only takes IP ID, no second parameter"
echo ""
echo "   Command:"
echo "   cast send $ADLV_ADDRESS \\"
echo "     \"createVault(bytes32)\" \\"
echo "     $IP_ID \\"
echo "     --rpc-url $RPC_URL \\"
echo "     --private-key $PRIVATE_KEY"
echo ""

echo "2. Update CVS (CANNOT CALL DIRECTLY)"
echo "   Function: updateCVS(bytes32,uint256)"
echo "   Note: Only ADLV contract (IDO owner) can call this"
echo "   Your address is NOT the owner"
echo ""
echo "   Options:"
echo "   a) Transfer IDO ownership back to your address (NOT RECOMMENDED)"
echo "      cast send $IDO_ADDRESS \\"
echo "        \"transferOwnership(address)\" \\"
echo "        YOUR_ADDRESS \\"
echo "        --rpc-url $RPC_URL \\"
echo "        --private-key $PRIVATE_KEY"
echo ""
echo "   b) Use the Agent Service to update CVS (RECOMMENDED)"
echo "      The agent service monitors events and updates CVS automatically"
echo ""

echo "3. Check Contract State"
echo ""
echo "   Check IDO owner:"
echo "   cast call $IDO_ADDRESS \"owner()\" --rpc-url $RPC_URL"
echo ""
echo "   Check if vault exists:"
echo "   cast call $ADLV_ADDRESS \"ipToVault(bytes32)(address)\" $IP_ID --rpc-url $RPC_URL"
echo ""
echo "   Get vault info:"
echo "   cast call $ADLV_ADDRESS \"getVault(address)\" VAULT_ADDRESS --rpc-url $RPC_URL"
echo ""

echo "=========================================="
echo "Quick Fix: Create Vault with Correct Command"
echo "=========================================="
echo ""
echo "Run this command to create a vault:"
echo ""
echo "cast send $ADLV_ADDRESS \\"
echo "  \"createVault(bytes32)\" \\"
echo "  $IP_ID \\"
echo "  --rpc-url $RPC_URL \\"
echo "  --private-key $PRIVATE_KEY"
echo ""

